# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 871f929fbcbdcb71fbc01670a83bed601f589863145e2193614fcdd4c4c8bcfed1e9fcd0f448e2dd812d9aeb50e671547562b78b91639ba718d23bc7dc2f7ca5

test:
  secret_key_base: 017d69b181110a4dbfc48cffac95fa6905181a0e53425c8fd62350915b45f175a05818da668e9260df93d5c242e069914e9b4064d5f1b101c6ebd11068ecd239

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
